name: Send mail

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  mail:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: true

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'
      
      - name: Send mail
        run: node mail.js
        env:
          PASS:  ${{ secrets.PASS }}
          DOMAIN: ${{ secrets.DOMAIN }}